import type { Product } from '@/types';
export const fallbackProducts:Product[]=[
{id:'mango-passion',slug:'mango-passion',name:'Mango Passion',short_description:'Mango, passionfruit and ginger in one bright tropical blend.',description:'A bold, sunny fruit elixir with ripe mango, tart passionfruit and a clean ginger finish.',price_minor:14500,currency:'EGP',category:'Tropical',featured:true,active:true,stock:48,ingredients:['Mango','Passionfruit','Ginger','Filtered water'],benefits:['Natural energy','Vitamin-rich fruit','Bright tropical flavour'],image_url:'/assets/product-mango-passion.webp',gallery:['/assets/product-mango-passion.webp','/assets/hero-splash-4k.webp']},
{id:'berry-glow',slug:'berry-glow',name:'Berry Glow',short_description:'A juicy berry blend with a bright, fresh finish.',description:'Deep berry flavour, clean acidity and a rich natural colour.',price_minor:15500,currency:'EGP',category:'Berry',featured:true,active:true,stock:36,ingredients:['Strawberry','Blueberry','Raspberry','Apple'],benefits:['Antioxidant-rich fruit','Fresh berry flavour','Naturally colourful'],image_url:'/assets/product-berry-glow.webp',gallery:['/assets/product-berry-glow.webp']},
{id:'lemon-yuzu',slug:'lemon-yuzu',name:'Lemon Yuzu',short_description:'Crisp citrus refreshment with a clean, sparkling lift.',description:'Bright lemon meets aromatic yuzu for an especially refreshing bottle.',price_minor:14000,currency:'EGP',category:'Citrus',featured:true,active:true,stock:42,ingredients:['Lemon','Yuzu','Filtered water','Mint'],benefits:['Refreshing citrus','Hydrating feel','Clean finish'],image_url:'/assets/product-lemon-yuzu.webp',gallery:['/assets/product-lemon-yuzu.webp']},
{id:'lavender-lemon',slug:'lavender-lemon',name:'Lavender Lemon',short_description:'Soft floral citrus for a calm, slow moment.',description:'Gentle lavender and bright lemon in one elegant blend.',price_minor:16500,currency:'EGP',category:'Botanical',featured:true,active:true,stock:28,ingredients:['Lemon','Lavender','Chamomile','Filtered water'],benefits:['Calm flavour profile','Botanical ingredients','Elegant finish'],image_url:'/assets/product-lavender-lemon.webp',gallery:['/assets/product-lavender-lemon.webp']}
];
export const bundles=[
{id:'immunity-bundle',slug:'shop',name:'The Immunity Bundle',price_minor:79000,currency:'EGP',image_url:'/assets/bundle-immunity.webp',description:'Six bottles centred on citrus, ginger and bright fruit.',stock:20},
{id:'wellness-bundle',slug:'shop',name:'The Wellness Bundle',price_minor:149000,currency:'EGP',image_url:'/assets/bundle-wellness.webp',description:'Twelve bottles for a complete fridge routine.',stock:20},
{id:'detox-bundle',slug:'shop',name:'The Detox Bundle',price_minor:82000,currency:'EGP',image_url:'/assets/bundle-detox.webp',description:'Six fresh green and citrus bottles.',stock:20}
];
export function formatMoney(value:number,currency='EGP'){return new Intl.NumberFormat('en-EG',{style:'currency',currency,maximumFractionDigits:2}).format(value/100)}
